#!/usr/bin/env bash

#######################
# LEMP Stack >> Install
#######################
# This is the master file.
# It calls and runs all other files and
# then erases itself.


# Reconfigure locales (after running do-locales)
sudo dpkg-reconfigure tzdata
sudo dpkg-reconfigure locales

# Call locales
sudo do-lemp