#!/usr/bin/env bash

############
# LEMP Stack
############

##
# FUNCTIONS
##
 
function green
{
	local message=${1:-"Ok"}
 
	echo -e "\033[32m${message}\033[0m"
}
 
function yellow
{
	local message=${1:-"Ok there"}
 
	echo -e "\033[33m${message}\033[0m"
}


##
# MAIN
##

# Initial update
green "Updating again (just in case, brotha')"
sudo apt-get update

# Tools
green "Installing basic tools"
sudo apt-get install -y vim unzip curl wget
sudo apt-get install -y tree
sudo apt-get install -y build-essential
sudo apt-get install -y python-software-properties

# PHP's cutting edge
green "Installing PHP's cutting edge"
sudo add-apt-repository ppa:ondrej/php5
sudo apt-get update

# Install PHP-FPM
green "Installing PHP-FPM"
sudo apt-get install -y php5-fpm

# Some PHP tools
sudo apt-get install -y php5-cli php5-mysql php5-curl php5-gd php5-mcrypt php5-xdebug

# Install Composer
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

# Install nginx
green "Installing nginx"
sudo add-apt-repository -y ppa:nginx/stable
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

# Configure PHP to work with nginx
green "Making PHP work with nginx"
sudo sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" /etc/php5/fpm/php.ini
service php5-fpm restart

# Install bash_it
green "Installing bash_it"
git clone https://github.com/revans/bash-it.git ~/.bash_it
~/.bash_it/install.sh
source ~/.bash_profile

# Bring .bash_aliases
green "Bringing some useful aliases"
curl https://gist.githubusercontent.com/crloscstillo/5c8c25df5c4ee878cb8e/raw/ebfd78467874eca1d172cb0e2c509e42c614cce0/bash_aliases.sh > ~/.bash_aliases
source ~/.bash_aliases
yellow "Know the aliases: https://gist.github.com/crloscstillo/5c8c25df5c4ee878cb8e"

# Install MySQL
green "Finally, install MySQL."
yellow "Your input will be needed"
sudo apt-get install -y mysql-server
mysql_secure_installation