#!/usr/bin/env bash

#######################
# LEMP Stack >> Locales
#######################
# Fix the locales

##
# FUNCTIONS
##
 
function green
{
	local message=${1:-"Ok"}
 
	echo -e "\033[32m${message}\033[0m"
}
 
function yellow
{
	local message=${1:-"Ok there"}
 
	echo -e "\033[33m${message}\033[0m"
}


##
# MAIN
##

# Call locales
green "Let's update this thing"
sudo apt-get update

# Generate locales
green "Declaring locales in .bashrc file"
sudo locale-gen en_US.UTF-8 es_CO.UTF-8

echo "# Locale fix" >> ~/.bashrc
echo export LC_CTYPE=en_US.UTF-8 >> ~/.bashrc
echo export LANGUAGE=en_US.UTF-8 >> ~/.bashrc
echo export LC_ALL=en_US.UTF-8 >> ~/.bashrc