#!/usr/bin/env bash

##############
# Virtual host
##############
# Handy script for creating
# virtual hosts on nginx

# Name of the virtual host
VHOST=${1}

# Ask for virtualhost's name
if [ -z "$VHOST" ]; then
  printf "What will be the \033[33mname of your virtual host\033[0m? "
  read -r VHOST
fi

curl https://gist.githubusercontent.com/crloscstillo/11148057/raw/a2c6eebaf6c0692c30ad19d88279131abfeda95d/nginx-vhost > ./${VHOST}

# Replace 'example.com' with the vhost name
sudo sed -i "s/example.com/${VHOST}/g" ${VHOST}

# Move the file to the configuration folder
sudo mv ${VHOST} /etc/nginx/sites-available/${VHOST}

# Symlink
sudo ln -s /etc/nginx/sites-available/${VHOST} /etc/nginx/sites-enabled/${VHOST}

# Test the configuration
nginx -t

# Restart nginx
sudo service nginx restart